# SonarCloud project configuration
# Place this file in the ROOT of your repository

sonar.projectKey=WhereAmI14_cPanel-access-log-reviewer
sonar.organization=ivan14sr

# Project info
sonar.projectName=cPanel-access-log-reviewer
sonar.projectVersion=1.0

# Source files - tells SonarCloud what to scan
sonar.sources=log_enrich.py,logs-reviewer-hybrid.sh,runner.sh,bash-variant


# Exclusions - don't scan these
sonar.exclusions=**/__pycache__/**,**/*.pyc,.git/**,**/.venv/**

# Python version
sonar.python.version=3.9
